const CONFIG = {
    BULLET_TIME_SCALE: 0.14,
    BULLET_TIME_DIM_ALPHA: 0.42,
    STAGE_INTRO_SLIDE_IN: 0.38,
    STAGE_INTRO_LABEL_HOLD: 0.85,
    STAGE_INTRO_SLIDE_OUT: 0.38,
    MONSTER_SPAWN_ANIM: 0.42,
    STAGE_CLEAR_FLASH: 0.55,
    STAGE_FAIL_LABEL_DURATION: 0.85,
    STAGE_FAIL_OVERLAY_FADE: 0.45,
    STAGE_INTRO_SAKURA_EXTRA: 0.8,
    FAIL_DEATH: {
        WINDUP: 0.3,
        SPEAR_STAGGER: 0.065,
        SPEAR_SPEED: 640,
        IMPACT_PAUSE: 0.24,
        DEATH_DURATION: 0.9,
        PLAYBACK_SPEED: 2,
    },
    NORMAL_TIME_SCALE: 1.0,

    COMBAT_RESOLVE: {
        FIRST_HIT_DELAY: 0.04,
        HIT_INTERVAL: 0.012,
        AFTERIMAGE_LIFE: 0.1,
        DEATH_STAGGER: 0.012,
    },

    MONSTER_DEATH_FADE: 0.1,

    DISPLAY: {
        LOGICAL_WIDTH: 390,
        LOGICAL_HEIGHT: 700,
        UNIT_SCALE: 1.3,
        NINJA_SPRITE_SCALE: 3,
        GRID_SIZE: 28,
    },

    PLAYER: {
        BASE_ATTACK: 95,
        BASE_HP: 100,
        BASE_KI: 234,
        BASE_CRIT_RATE: 0.08,
        BASE_CRIT_DAMAGE: 1.6,
        ATTACK_SPEED: 2300,
        HITBOX_RADIUS: 12,
        TRIGGER_RADIUS_RATIO: 0.06,
        TRIGGER_RADIUS_MIN: 30,
        KI_PER_PIXEL: 0.18,
        SIZE_SCALE: 1.0,
        INVINCIBLE_TIME: 0.45,
        DAMAGE_FLASH_TIME: 0.42,
        COMBO_DAMAGE_BONUS: 0.01,
        COMBO_DISPLAY_HOLD: 0.6,
        COMBO_END_FADE: 0.4,
        COMBO_TEXT_BASE: 30,
        COMBO_TEXT_GROW: 1.4,
        COMBO_TEXT_MAX_GROW: 22,
        COMBO_SHAKE_DURATION: 0.24,
        KI_REGEN_RATE: 104,
    },

    EXP: {
        BASE_TO_LEVEL: 100,
        GROWTH: 1.22,
        BAR_HEIGHT: 24,
        KILL_REWARD: {
            NORMAL: 2,
            ELITE: 4,
            SHIELD: 3,
            BERSERKER: 4,
            SPLITTER: 3,
            ARCHER: 3,
            FIRE_MAGE: 3,
        },
    },

    // 火柱半径 ≈ 黑洞基础半径(82) 的一半
    FIRE_PILLAR: {
        RADIUS: 60,
        WARNING_TIME: 1.1,
        ACTIVE_TIME: 0.5,
        FADE_TIME: 0.3,
        DAMAGE: 16,
    },

    ARROW: {
        RADIUS: 6,
        SPEED: 85,
    },

    STAGE_MONSTER_SCALE: 1.3,
    STAGE_COUNT_MUL: 2 / 3,
    SHIELD_COUNT_MUL: 1 / 3,

    // 关卡递增：第 1 关系数 1.0，每往后一关 HP/DEF 按幂次增长
    STAGE_STAT_SCALE: {
        HP_GROWTH: 1.3,
        DEF_GROWTH: 1.3,
    },

    SPAWN: {
        MIN_DIST_FROM_PLAYER: 100,
        MIN_MONSTER_SPACING: 20,
        CLUSTER_COUNT_MIN: 5,
        CLUSTER_COUNT_MAX: 9,
        CLUSTER_PICK_CHANCE: 0.74,
        SPARSE_PICK_CHANCE: 0.26,
    },

    STAGES: [
        { normal: 56, elite: 0, shield: 0, berserker: 0, splitter: 0, archer: 0, fireMage: 0 },
        { normal: 60, elite: 12, shield: 0, berserker: 0, splitter: 0, archer: 10, fireMage: 0 },
        { normal: 64, elite: 20, shield: 8, berserker: 0, splitter: 0, archer: 12, fireMage: 6 },
        { normal: 64, elite: 20, shield: 12, berserker: 8, splitter: 0, archer: 14, fireMage: 7 },
        { normal: 68, elite: 24, shield: 12, berserker: 8, splitter: 0, archer: 16, fireMage: 8 },
        { normal: 68, elite: 24, shield: 16, berserker: 12, splitter: 0, archer: 18, fireMage: 9 },
        { normal: 72, elite: 28, shield: 20, berserker: 12, splitter: 0, archer: 20, fireMage: 10 },
        { normal: 76, elite: 28, shield: 24, berserker: 16, splitter: 0, archer: 22, fireMage: 11 },
    ],

    MONSTERS: {
        NORMAL: {
            name: '普通怪',
            hp: 80,
            def: 4,
            attack: 10,
            attackInterval: 1.15,
            size: 13,
            speed: 19,
            color: '#526078',
            grade: 'B',
            canMove: true,
        },
        ELITE: {
            name: '高级怪',
            hp: 110,
            def: 6,
            attack: 14,
            attackInterval: 1.05,
            size: 14,
            speed: 21,
            color: '#8a6aa8',
            grade: 'B+',
            canMove: true,
        },
        SHIELD: {
            name: '盾牌怪',
            hp: 120,
            def: 5,
            attack: 12,
            attackInterval: 1.25,
            size: 15,
            speed: 16,
            color: '#5f7a88',
            grade: 'B+',
            canMove: true,
        },
        BERSERKER: {
            name: '狂战士',
            hp: 90,
            def: 2,
            attack: 18,
            attackInterval: 0.85,
            size: 14,
            speed: 26,
            color: '#b85a4a',
            grade: 'C/B',
            canMove: true,
            kiDrainOnHit: 10,
        },
        SPLITTER: {
            name: '分裂怪',
            hp: 70,
            def: 2,
            attack: 8,
            attackInterval: 1.2,
            size: 18,
            speed: 14,
            color: '#7b9f5a',
            grade: 'A+/C/C',
            canMove: true,
            maxSplitTier: 3,
            splitCount: 2,
        },
        ARCHER: {
            name: '射箭怪',
            hp: 75,
            def: 3,
            attack: 12,
            attackInterval: 1.35,
            attackRange: 215,
            arrowSpeed: 85,
            size: 12,
            speed: 17,
            color: '#6a8a5a',
            grade: 'B',
            canMove: true,
            ranged: true,
        },
        FIRE_MAGE: {
            name: '火焰法师',
            hp: 70,
            def: 2,
            attack: 16,
            attackInterval: 2.4,
            attackRange: 250,
            size: 12,
            speed: 15,
            color: '#501818',
            grade: 'B',
            canMove: true,
            ranged: true,
        },
    },

    BUFF_ORB: {
        BASE_TYPES: ['attack', 'ki', 'combo'],
        RADIUS: 13,
        MAX_PER_TYPE: 4,
        SPAWN_CHANCE: {
            attack: 0.55,
            ki: 0.45,
            combo: 0.42,
            ice: 0.28,
        },
        EXTRA_SPAWN_CHANCE: 0.48,
        MIN_KI_PER_STAGE: 2,
    },

    UPGRADE_RARITY: {
        white: { chance: 0.60, color: '#d8d8d8', name: '白色' },
        blue: { chance: 0.25, color: '#58a8ff', name: '蓝色' },
        purple: { chance: 0.10, color: '#b070ff', name: '紫色' },
        orange: { chance: 0.05, color: '#ff9830', name: '橙色' },
    },

    SHAKE: {
        NORMAL: { magnitude: 3, duration: 0.1 },
        CRIT: { magnitude: 8, duration: 0.22 },
        COMBO_MAG_PER_HIT: 0.1,
        COMBO_MAG_CAP: 1.5,
    },
};
